captainVersion: 4
services:
  $$cap_appname:
    image: neosmemo/memos:$$cap_memos_version
    restart: unless-stopped
    volumes:
      - $$cap_appname-memos-data:/var/opt/memos
    caproverExtra:
      containerHttpPort: 5230
caproverOneClickApp:
  variables:
    - id: '$$cap_memos_version'
      label: Memos Version
      defaultValue: 0.13.2
      description: Check out their Docker page for the valid tags https://hub.docker.com/r/neosmemo/memos/tags
      validRegex: '/.{1,}/'
  instructions:
    start: |-
      A description that will be displayed to the user when they
      are installing one click app!
      It can be multiline and contain more details and probably special
      hardware requirements!
    end: |-
      A summary when the app is deployed!
      It can be multiline.

      It can also include the dynamic parameters such as
      $$cap_appname and $$cap_other_random_char
  displayName: Memos
  isOfficial: true
  description: A lightweight, self-hosted memo hub.  Open Source and Free forever.
  documentation: Built using files found from at https://github.com/usememos/memos
